.\" Copyright, the authors of the Linux man-pages project
.\"
.\" SPDX-License-Identifier: Linux-man-pages-copyleft
.\"
.TH countof 3 2026-02-10 "Linux man-pages (unreleased)"
.SH NAME
countof, _Countof \- count the number of elements in an array
.SH LIBRARY
Standard C library
.RI ( libc )
.SH SYNOPSIS
.nf
.B #include <stdcountof.h>
.P
.BI "size_t countof(" array );
.fi
.SH DESCRIPTION
This operator counts the number of elements in an array.
.P
If the operand is not an array,
it produces a compilation error.
.P
There's a keyword,
.BR \%_Countof (),
that behaves identically,
and can be used without including
.IR <stdcountof.h> .
.SH RETURN VALUE
The number of elements in the array.
.SH STANDARDS
C2y.
.SH HISTORY
gcc 16, clang 21, gnulib 202507.
.SH SEE ALSO
.BR operator (7)
