'\" t
.\" Copyright, the authors of the Linux man-pages project
.\"
.\" SPDX-License-Identifier: Linux-man-pages-copyleft
.\"
.TH pvalloc 3 2025-12-13 "Linux man-pages (unreleased)"
.SH NAME
pvalloc
\-
page-sized page-aligned memory allocation
.SH LIBRARY
Standard C library
.RI ( libc ,\~ \-lc )
.SH SYNOPSIS
.nf
.B #include <malloc.h>
.P
.BI "[[deprecated]] void *pvalloc(size_t " size );
.fi
.SH DESCRIPTION
.BR pvalloc ()
is similar to
.BR valloc (),
but rounds the size of the allocation up to
the next multiple of the system page size.
.SH ATTRIBUTES
For an explanation of the terms used in this section, see
.BR attributes (7).
.TS
allbox;
lbx lb lb
l l l.
Interface	Attribute	Value
T{
.na
.nh
.BR pvalloc ()
T}	Thread safety	MT-Unsafe init
.TE
.SH STANDARDS
GNU.
.SH HISTORY
glibc 2.0.
.SH CAVEATS
See
.BR valloc (3).
.SH SEE ALSO
.BR valloc (3)
