.\" Copyright 1994-1995, Daniel Quinlan <Daniel.Quinlan@linux.org>
.\" Copyright 2002-2017, Michael Kerrisk <mtk.manpages@gmail.com>
.\" Copyright, the authors of the Linux man-pages project
.\"
.\" SPDX-License-Identifier: GPL-3.0-or-later
.\"
.TH proc_pid_cgroup 5 2026-02-08 "Linux man-pages (unreleased)"
.SH NAME
/proc/pid/cgroup \- control group
.SH DESCRIPTION
.TP
.IR /proc/ pid /cgroup " (since Linux 2.6.24)"
See
.BR cgroups (7).
.SH SEE ALSO
.BR proc (5)
