'\" t
.\" Copyright 1989-1993, The Regents of the University of California.
.\" Copyright, the authors of the Linux man-pages project
.\"
.\" SPDX-License-Identifier: BSD-3-Clause
.\"
.TH operator 7 2025-12-01 "Linux man-pages (unreleased)"
.SH NAME
operator \- C operator precedence and order of evaluation
.SH DESCRIPTION
This manual page lists C operators and their precedence in evaluation.
.P
.TS
lb lb lb
l l l.
Operator	Associativity	Notes
() _Generic()	-	[1]
[] () . \-> ++ \-\- (type){}	left to right	[2] [3]
T{
++ \-\- & * + \- \[ti] ! _Countof sizeof alignof _Maxof _Minof
T}	right to left	[4]
(type)	right to left
* / %	left to right
+ \-	left to right
<< >>	left to right
< > <= >=	left to right
== !=	left to right
&	left to right
\[ha]	left to right
|	left to right
&&	left to right
||	left to right
?:	right to left
= *= /= %= += \-= <<= >>= &= \[ha]= |=	right to left
,	left to right
.TE
.P
The following notes provide further information to the above table:
.P
.PD 0
.IP [1] 5
The () at this precedence is the parenthesized expression.
.IP [2]
The () at this precedence is the function call operator.
.IP [3]
The ++ and \-\- operators at this precedence level are
the postfix flavors of the operators.
.IP [4]
The ++ and \-\- operators at this precedence level are
the prefix flavors of the operators.
.PD
