.\" Copyright, the authors of the Linux man-pages project
.\"
.\" SPDX-License-Identifier: Linux-man-pages-copyleft
.\"
.TH mansectf 1 2026-01-30 "Linux man-pages (unreleased)"
.SH NAME
mansectf
\-
format specific sections of manual pages
.SH SYNOPSIS
.SY mansectf
.I section
.RI [ file \~.\|.\|.]
.YS
.SH DESCRIPTION
The
.B mansectf
command formats specific sections of manual-page files.
.SH PARAMETERS
See
.BR mansect (1).
.SH ENVIRONMENT
See
.BR man (1).
.SH EXAMPLES
.EX
.RB $\~ "man \-w strtol strtoul | xargs mansectf \[aq]NAME|SEE ALSO\[aq] | cat";
strtol(3)           Library Functions Manual          strtol(3)
\&
NAME
     strtol, strtoll, strtoq - convert a string to a long inte‐
     ger
\&
SEE ALSO
     atof(3),  atoi(3),  atol(3), strtod(3), strtoimax(3), str‐
     toul(3)
\&
Linux man‐pages 6.16       2025‐12‐01                 strtol(3)
---------------------------------------------------------------
strtoul(3)          Library Functions Manual         strtoul(3)
\&
NAME
     strtoul, strtoull, strtouq - convert a string  to  an  un‐
     signed long integer
\&
SEE ALSO
     a64l(3),  atof(3), atoi(3), atol(3), strtod(3), strtol(3),
     strtoumax(3)
\&
Linux man‐pages 6.16       2025‐09‐21                strtoul(3)
.EE
.SH SEE ALSO
.BR lexgrog (1),
.BR groff (1),
.BR pcre2grep (1),
.BR mandb (8)
